### ISSUE TITLE
https://github.com/amirfeizi/otargen/blob/main/R/overlapInfoForStudy.R

### ISSUE THREAD

**Issue by vb-mohd** [amirfeizi/otargen#8]
Hi Amir et al,

Thanks for writing this wonderful R package.

May I suggest a minor change in `https://github.com/amirfeizi/otargen/blob/main/R/overlapInfoForStudy.R`?

In line 47, you might need to delete or hash out the following for the code to work with user-inputted study ids:

`  variables <- list(studyId = "GCST90002357", studyIds = list("GCST90025975", "GCST90025962"))
`

Best wishes,
Mohd

**Comment by amirfeizi** [comment]
Hi Mohd,

Thanks for using `otargen`; I appreciate spotting this bug for `overlapInfoForStudy()`. I will fix this one right away!

Kind regards,

Amir

**Comment by amirfeizi** [comment]
Thanks again, Mohd, for noticing this bug; it is now fixed and updated in `CRAN` and the repository.

Best,

Amir
