### ISSUE TITLE
Package ‘otargen’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by esebesty** [amirfeizi/otargen#9]
Looks like otargen was [removed from CRAN](https://cran.r-project.org/web/packages/otargen/) for policy violation.

```
> install.packages("otargen", repos = "https://cloud.r-project.org")
Warning message:
package ‘otargen’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
>
```

Any idea what happened? I can still install it from github, using `devtools` or download a `.tar.gz` archive of the repo and use `install.packages()` with that, but CRAN would be much more convenient.

**Comment by amirfeizi** [comment]
@esebesty thanks for reporting this issue! I will check to see what was the reason and resubmit it into the CRAN, which is as you mentioned is more convenient.

Kind regards,

Amir

**Comment by amirfeizi** [comment]
@esebesty I have now submitted the new `otargen `release to CRAN which includes several new useful queries that have been frequently requested to be added to the package which use Open Target API instead to collect the relevant data including: `chemblQuery(), clinvarQuery(), knownDrugsQuery(), compGenomicsQuery(), mousePhenotypesQuery`. It will take few days to CRAN to approve and add it back, meanwhile you can use the updated version from github repo.

I will close now this issue
